In [ ]:
import numpy as np 

In [37]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.ones(4)

array([1., 1., 1., 1.])

In [40]:
np.full(12,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [42]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [44]:
arr[2]=34

In [45]:
arr

array([ 1,  2, 34,  4,  5])

In [48]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr = np.arange(10)
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [54]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Multi d array 

In [56]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [65]:
n=np.array([
            [1,2,3],    
            [4,5,6],    
            [7,8,9]
            ] )

In [66]:
n[0,2] = 7

In [67]:
n

array([[1, 2, 7],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
n[0]

array([1, 2, 7])

In [69]:
n[1]

array([4, 5, 6])

In [70]:
mylist = [10,20,30,40,50]
np.array(mylist)

array([10, 20, 30, 40, 50])

In [74]:
np.random.seed(1)  
random_array = np.random.rand(5, 2)
random_array 

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01]])

random generated array 

In [ ]:
np.random.seed(2)  # Set the seed => Pain the result 
np.random.rand(3,4)



array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097],
       [0.29965467, 0.26682728, 0.62113383, 0.52914209]])

In [79]:
np.random.seed(2)  # Set the seed => Pain the result 
100*np.random.randn(3,4)


array([[ -41.67578474,   -5.62668272, -213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657,   50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149,   55.14540445,  229.22080128]])

Element wise operator 


In [80]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [82]:
a+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
a/2


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

Comarision  Op


In [84]:
a>=2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [88]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sumarization 

In [90]:
b.min()

np.int64(0)

In [91]:
b.max()

np.int64(9)

In [92]:
b.sum()

np.int64(45)

ALL IMPORTANT NUMPY    BY:HOMOSA
